version: 1
jobs:
  build-and-deploy:
    steps:
      - cd backend
      - npm install
      - npm run build
      - cd ..
      - npm install -g zcatalyst-cli@beta
      - catalyst appsail deploy --service-name foodlobby-backend --stack node20
stages:
  - name: deploy
    jobs:
      - build-and-deploy