import { useState, useEffect, useCallback } from 'react';
import api from '../../services/api';

interface InviteToken {
  id: number;
  token: string;
  type: 'marketing' | 'member';
  invited_email: string;
  invited_by_username: string | null;
  status: 'pending' | 'used' | 'expired' | 'revoked';
  expires_at: string;
  used_at: string | null;
  created_at: string;
}

export default function AdminInvites(): JSX.Element {
  const [invites, setInvites] = useState<InviteToken[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState<string>('all');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [actionLoading, setActionLoading] = useState<number | null>(null);
  const [toast, setToast] = useState<{ msg: string; ok: boolean } | null>(null);

  // Generate invite form state
  const [showForm, setShowForm] = useState(false);
  const [genEmail, setGenEmail] = useState('');
  const [genType, setGenType] = useState<'marketing' | 'member'>('marketing');
  const [genLoading, setGenLoading] = useState(false);
  const [generatedUrl, setGeneratedUrl] = useState<string | null>(null);

  const showToast = (msg: string, ok = true) => {
    setToast({ msg, ok });
    setTimeout(() => setToast(null), 3500);
  };

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get('/admin/invites');
      setInvites(res.data.invites || []);
    } catch {
      showToast('Failed to load invites', false);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const revoke = async (id: number, email: string) => {
    if (!window.confirm(`Revoke invite for ${email}?`)) return;
    setActionLoading(id);
    try {
      await api.delete(`/admin/invites/${id}/revoke`);
      showToast('Invite revoked');
      load();
    } catch {
      showToast('Failed to revoke invite', false);
    } finally {
      setActionLoading(null);
    }
  };

  const copyLink = (token: string) => {
    const url = `${window.location.origin}/register?invite=${token}`;
    navigator.clipboard.writeText(url).then(() => showToast('Link copied to clipboard'));
  };

  const generateInvite = async () => {
    if (!genEmail.trim()) return;
    setGenLoading(true);
    setGeneratedUrl(null);
    try {
      const res = await api.post('/invite/generate', { email: genEmail, type: genType });
      const url = `${window.location.origin}/register?invite=${res.data.token}`;
      setGeneratedUrl(url);
      showToast('Invite generated');
      setGenEmail('');
      load();
    } catch (err: any) {
      showToast(err?.response?.data?.error || 'Failed to generate invite', false);
    } finally {
      setGenLoading(false);
    }
  };

  const typeBadge = (type: string) => (
    <span style={{
      padding: '2px 9px', borderRadius: 12, fontSize: 11, fontWeight: 700,
      backgroundColor: type === 'marketing' ? '#dbeafe' : '#d1fae5',
      color: type === 'marketing' ? '#1d4ed8' : '#065f46',
      textTransform: 'uppercase', letterSpacing: '0.05em',
    }}>
      {type}
    </span>
  );

  const statusBadge = (status: string) => {
    const map: Record<string, string> = { pending: '#f59e0b', used: '#10b981', expired: '#9ca3af', revoked: '#ef4444' };
    return (
      <span style={{
        padding: '2px 9px', borderRadius: 12, fontSize: 11, fontWeight: 600,
        backgroundColor: (map[status] || '#9ca3af') + '20', color: map[status] || '#9ca3af',
      }}>
        {status}
      </span>
    );
  };

  const filtered = invites.filter(inv =>
    (filterType === 'all' || inv.type === filterType) &&
    (filterStatus === 'all' || inv.status === filterStatus)
  );

  const isExpired = (d: string) => new Date(d) < new Date();

  return (
    <div>
      {toast && (
        <div style={{
          position: 'fixed', top: 20, right: 20, zIndex: 9999,
          padding: '12px 20px', borderRadius: 8, color: 'white',
          backgroundColor: toast.ok ? '#16a34a' : '#dc2626', fontWeight: 500,
        }}>
          {toast.msg}
        </div>
      )}

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, color: '#111827' }}>Invite Tokens</h1>
          <p style={{ color: '#6b7280', marginTop: 4 }}>All invite links generated by admin or members.</p>
        </div>
        <button
          onClick={() => { setShowForm(!showForm); setGeneratedUrl(null); }}
          style={{
            padding: '9px 20px', borderRadius: 8, border: 'none', cursor: 'pointer',
            backgroundColor: '#15803d', color: 'white', fontWeight: 600, fontSize: 14,
          }}
        >
          + Generate Invite
        </button>
      </div>

      {/* Generate Form */}
      {showForm && (
        <div style={{
          backgroundColor: 'white', border: '1px solid #d1fae5', borderRadius: 10,
          padding: 20, marginBottom: 20,
        }}>
          <h3 style={{ margin: '0 0 16px', fontSize: 15, color: '#15803d' }}>Generate a New Invite Link</h3>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'flex-end' }}>
            <div style={{ flex: 1, minWidth: 220 }}>
              <label style={{ display: 'block', fontSize: 12, color: '#6b7280', marginBottom: 4 }}>Email Address</label>
              <input
                type="email"
                value={genEmail}
                onChange={e => setGenEmail(e.target.value)}
                placeholder="recipient@example.com"
                style={{
                  width: '100%', padding: '8px 12px', borderRadius: 6,
                  border: '1px solid #d1d5db', fontSize: 14, boxSizing: 'border-box',
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: 12, color: '#6b7280', marginBottom: 4 }}>Invite Type</label>
              <select
                value={genType}
                onChange={e => setGenType(e.target.value as 'marketing' | 'member')}
                style={{ padding: '8px 12px', borderRadius: 6, border: '1px solid #d1d5db', fontSize: 14 }}
              >
                <option value="marketing">Marketing (Direct Access)</option>
                <option value="member">Member (Pending Review)</option>
              </select>
            </div>
            <button
              onClick={generateInvite}
              disabled={genLoading || !genEmail}
              style={{
                padding: '9px 20px', borderRadius: 6, border: 'none', cursor: 'pointer',
                backgroundColor: '#15803d', color: 'white', fontWeight: 600, fontSize: 13,
                opacity: genLoading || !genEmail ? 0.6 : 1,
              }}
            >
              {genLoading ? 'Generating...' : 'Generate'}
            </button>
          </div>

          {generatedUrl && (
            <div style={{
              marginTop: 14, padding: '10px 14px', borderRadius: 6,
              backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0',
            }}>
              <div style={{ fontSize: 12, color: '#15803d', fontWeight: 600, marginBottom: 4 }}>Invite link generated:</div>
              <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
                <code style={{ fontSize: 12, color: '#374151', wordBreak: 'break-all', flex: 1 }}>{generatedUrl}</code>
                <button
                  onClick={() => navigator.clipboard.writeText(generatedUrl!).then(() => showToast('Copied!'))}
                  style={{
                    padding: '4px 12px', borderRadius: 5, border: '1px solid #16a34a',
                    backgroundColor: 'white', color: '#16a34a', cursor: 'pointer', fontSize: 12, fontWeight: 600,
                  }}
                >
                  Copy
                </button>
              </div>
              <div style={{ fontSize: 11, color: '#6b7280', marginTop: 4 }}>
                Valid for 30 days · Single use · Locked to {genEmail || 'email above'}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Filters */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 20, flexWrap: 'wrap', alignItems: 'center' }}>
        <select
          value={filterType}
          onChange={e => setFilterType(e.target.value)}
          style={{ padding: '6px 12px', borderRadius: 6, border: '1px solid #d1d5db', fontSize: 13 }}
        >
          <option value="all">All Types</option>
          <option value="marketing">Marketing</option>
          <option value="member">Member</option>
        </select>
        <select
          value={filterStatus}
          onChange={e => setFilterStatus(e.target.value)}
          style={{ padding: '6px 12px', borderRadius: 6, border: '1px solid #d1d5db', fontSize: 13 }}
        >
          <option value="all">All Status</option>
          <option value="pending">Pending</option>
          <option value="used">Used</option>
          <option value="expired">Expired</option>
          <option value="revoked">Revoked</option>
        </select>
        <span style={{ marginLeft: 'auto', fontSize: 13, color: '#9ca3af' }}>{filtered.length} results</span>
        <button
          onClick={load}
          style={{
            padding: '6px 14px', borderRadius: 6, border: '1px solid #d1d5db',
            backgroundColor: 'white', cursor: 'pointer', fontSize: 13,
          }}
        >
          ↻
        </button>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: 40, color: '#9ca3af' }}>Loading...</div>
      ) : filtered.length === 0 ? (
        <div style={{
          textAlign: 'center', padding: 60, backgroundColor: 'white',
          borderRadius: 10, border: '1px solid #e5e7eb', color: '#9ca3af',
        }}>
          No invites found.
        </div>
      ) : (
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', backgroundColor: 'white', borderRadius: 10, overflow: 'hidden', border: '1px solid #e5e7eb' }}>
            <thead>
              <tr style={{ backgroundColor: '#f9fafb', borderBottom: '1px solid #e5e7eb' }}>
                {['Invited Email', 'Type', 'Status', 'Sent By', 'Created', 'Expires', 'Actions'].map(h => (
                  <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontSize: 12, fontWeight: 600, color: '#6b7280', whiteSpace: 'nowrap' }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((inv, i) => (
                <tr key={inv.id} style={{
                  borderBottom: i < filtered.length - 1 ? '1px solid #f3f4f6' : 'none',
                  opacity: inv.status === 'revoked' ? 0.6 : 1,
                }}>
                  <td style={{ padding: '11px 14px', fontSize: 13, color: '#111827', fontWeight: 500 }}>
                    {inv.invited_email}
                  </td>
                  <td style={{ padding: '11px 14px' }}>{typeBadge(inv.type)}</td>
                  <td style={{ padding: '11px 14px' }}>
                    {statusBadge(isExpired(inv.expires_at) && inv.status === 'pending' ? 'expired' : inv.status)}
                  </td>
                  <td style={{ padding: '11px 14px', fontSize: 13, color: '#6b7280' }}>
                    {inv.invited_by_username || <span style={{ color: '#d1d5db' }}>Admin</span>}
                  </td>
                  <td style={{ padding: '11px 14px', fontSize: 12, color: '#9ca3af', whiteSpace: 'nowrap' }}>
                    {new Date(inv.created_at).toLocaleDateString('en-IN')}
                  </td>
                  <td style={{ padding: '11px 14px', fontSize: 12, whiteSpace: 'nowrap',
                    color: isExpired(inv.expires_at) ? '#ef4444' : '#9ca3af',
                  }}>
                    {new Date(inv.expires_at).toLocaleDateString('en-IN')}
                  </td>
                  <td style={{ padding: '11px 14px' }}>
                    <div style={{ display: 'flex', gap: 6 }}>
                      {inv.status === 'pending' && !isExpired(inv.expires_at) && (
                        <>
                          <button
                            onClick={() => copyLink(inv.token)}
                            title="Copy link"
                            style={{
                              padding: '4px 10px', borderRadius: 5, border: '1px solid #d1d5db',
                              backgroundColor: 'white', cursor: 'pointer', fontSize: 12,
                            }}
                          >
                            📋 Copy
                          </button>
                          <button
                            onClick={() => revoke(inv.id, inv.invited_email)}
                            disabled={actionLoading === inv.id}
                            style={{
                              padding: '4px 10px', borderRadius: 5, border: '1px solid #fca5a5',
                              backgroundColor: 'white', color: '#dc2626', cursor: 'pointer', fontSize: 12,
                              opacity: actionLoading === inv.id ? 0.6 : 1,
                            }}
                          >
                            Revoke
                          </button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
